# scripts/ai_engine.py
import os
import sqlite3
import json
import chromadb
from chromadb.utils import embedding_functions
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

# System Paths
DB_PATH = os.path.join(os.path.dirname(__file__), "../data/recipes.db")
CHROMA_PATH = os.path.join(os.path.dirname(__file__), "../data/chroma_db")

# 1. Initialize System Clients
client = Groq(api_key=os.getenv("GROQ_API_KEY"))
chroma_client = chromadb.PersistentClient(path=CHROMA_PATH)

# Using local all-MiniLM-L6-v2 embeddings to show end-to-end ML pipelining
embedding_func = embedding_functions.SentenceTransformerEmbeddingFunction(model_name="all-MiniLM-L6-v2")
vector_collection = chroma_client.get_or_create_collection(name="recipe_transcripts", embedding_function=embedding_func)

def sync_sqlite_to_vector_db():
    """Pipeline component: Syncs raw text transcripts from SQLite to Vector Space."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute("""
        SELECT r.id, r.recipe_name, r.transcript, re.caption, re.url 
        FROM recipes r 
        JOIN reels re ON r.reel_id = re.id
    """)
    rows = cursor.fetchall()
    conn.close()

    for recipe_id, name, transcript, caption, url in rows:
        combined_text = f"Recipe: {name}\nTranscript: {transcript}\nCaption: {caption}"
        # Upsert into ChromaDB vector index
        vector_collection.upsert(
            documents=[combined_text],
            metadatas=[{"recipe_name": name, "url": url, "database_id": recipe_id}],
            ids=[str(recipe_id)]
        )
    return len(rows)

def tool_sql_query_executor(sql_query):
    """Agent Tool: Executes safe, read-only analytical queries against SQLite."""
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    try:
        cursor.execute(sql_query)
        columns = [desc[0] for desc in cursor.description]
        results = [dict(zip(columns, row)) for row in cursor.fetchall()]
        return json.dumps(results)
    except Exception as e:
        return json.dumps({"error": f"Invalid SQL generated by Agent: {str(e)}"})
    finally:
        conn.close()

def tool_semantic_vector_search(semantic_query, n_results=3):
    """Agent Tool: Queries Vector DB using embedding distance matrix for fuzzy extraction."""
    results = vector_collection.query(
        query_texts=[semantic_query],
        n_results=int(n_results)
    )
    
    extracted_context = []
    if results['documents']:
        for doc, metadata in zip(results['documents'][0], results['metadatas'][0]):
            extracted_context.append({
                "source_text": doc,
                "recipe_name": metadata["recipe_name"],
                "url": metadata["url"]
            })
    return json.dumps(extracted_context)

def orchestrate_agent_response(user_query):
    """Supervisor Agent: Analyzes runtime intent and dispatches specialized execution paths."""
    
    # Declare advanced micro-tools to the Supervisor Agent
    tools = [
        {
            "type": "function",
            "function": {
                "name": "tool_sql_query_executor",
                "description": "Run read-only database tracking operations. Use ONLY when user asks for exact aggregate counts, list of distinct categories, or structural mappings.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "sql_query": {
                            "type": "string",
                            "description": "Valid SQLite string. Tables: reels(id, url, status, creator_username), recipes(id, reel_id, recipe_name, transcript), ingredients(id, recipe_id, name, category)."
                        }
                    },
                    "required": ["sql_query"]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "tool_semantic_vector_search",
                "description": "Fuzzy query matching tool. Use when user asks based on flavor profiles, leftovers, mood, duration, styles, or missing items.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "semantic_query": {
                            "type": "string",
                            "description": "Fuzzy raw string highlighting ingredients or concepts, e.g., 'high protein quick meal with garlic'"
                        },
                        "n_results": {"type": "integer", "default": 3}
                    },
                    "required": ["semantic_query"]
                }
            }
        }
    ]

    messages = [
        {
            "role": "system",
            "content": (
                "You are an Advanced AI Agent Orchestrator. Break down queries dynamically. "
                "If the data needs precise count metrics, compile structural SQLite queries. "
                "If the query focuses on ingredients or culinary styles, dispatch Vector Searches."
            )
        },
        {"role": "user", "content": user_query}
    ]

    # Step 1: LLM Tool Routing Decision Execution
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=messages,
        tools=tools,
        tool_choice="auto",
        temperature=0.1
    )
    
    response_message = response.choices[0].message
    tool_calls = response_message.tool_calls

    # Step 2: Intermediate Multi-Tool Execution Processing
    if tool_calls:
        available_tools = {
            "tool_sql_query_executor": tool_sql_query_executor,
            "tool_semantic_vector_search": tool_semantic_vector_search
        }
        
        messages.append(response_message)
        
        for call in tool_calls:
            function_name = call.function.name
            tool_function = available_tools[function_name]
            arguments = json.loads(call.function.arguments)
            
            # Execute selected backend tool
            tool_result = tool_function(**arguments)
            
            messages.append({
                "role": "tool",
                "tool_call_id": call.id,
                "name": function_name,
                "content": tool_result
            })
        
        # Step 3: Synthesis Generation
        final_response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=messages,
            temperature=0.3
        )
        return final_response.choices[0].message.content
        
    return response_message.content